{{- if .Values.fastapiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-chart.fullname" . }}-app-secrets
  labels:
    {{- include "fastapi-chart.labels" . | nindent 4 }}
type: Opaque
data:
  fastapi-key: {{ .Values.fastapiKey | b64enc | quote }}
  database-url: {{ .Values.databaseUrl | b64enc | quote }}
{{- end }}
