{{- if .Values.postgresql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-chart.fullname" . }}-db-secret
  labels:
    {{- include "fastapi-chart.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.password | b64enc | quote }}
{{- end }}
